baseURL = "https://www.nephrogo.com/"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
assetDir = "static"
enableRobotsTXT = true
googleAnalytics = "G-YXL4JPN3HT"

[imaging]
resampleFilter = "lanczos"
quality = 85

[languages]
  [languages.en]
    privacyPolicyPath = "documents/en/privacy-policy.pdf"
    fairUseRulesPath = "documents/en/fair-use-rules.pdf"
    nutritionScreenshot = "img/app/lt/screen-nutrition.png"
    healthStatusScreenshot = "img/app/lt/screen-health-status.png"
    peritonealDialysisScreenshot = "img/app/lt/screen-peritoneal-dialysis.png"
    socialCover = "img/social-cover-de.png"