baseURL = "https://www.nephrogo.de/"
defaultContentLanguage = "de"
disableKinds = ["taxonomy", "taxonomyTerm"]
assetDir = "static"
enableRobotsTXT = true
googleAnalytics = "G-YV5R2M9BQN"

[imaging]
resampleFilter = "lanczos"
quality = 85

[languages]
  [languages.de]
    privacyPolicyPath = "documents/de/privacy-policy.pdf"
    fairUseRulesPath = "documents/de/fair-use-rules.pdf"
    nutritionScreenshot = "img/app/de/screen-nutrition.png"
    healthStatusScreenshot = "img/app/de/screen-health-status.png"
    peritonealDialysisScreenshot = "img/app/de/screen-peritoneal-dialysis.png"
    socialCover = "img/social-cover-de.png"