baseURL = "https://www.nephrogo.de/"
defaultContentLanguage = "de"
disableKinds = ["taxonomy", "taxonomyTerm"]
assetDir = "static"
enableRobotsTXT = true
googleAnalytics = "G-YV5R2M9BQN"

[imaging]
resampleFilter = "lanczos"
quality = 85

[languages]
  [languages.de]
