baseURL = "https://www.nephrogo.com/"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
assetDir = "static"
enableRobotsTXT = true
googleAnalytics = "G-YXL4JPN3HT"

[imaging]
resampleFilter = "lanczos"
quality = 85

[languages]
  [languages.en]
